### ISSUE TITLE
declaring function impacts other function

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#105]
The next enigma:
Now having a reasonably well working substr() I copied that over to another directory where some experiments are going on. It did not work well. This returns, for the last call, 7890...... , which are some dots too many. Now if I comment out the call to length() and its declaration, it works ok again and gives me 7890.... , so correctly observing the call to length. 
```
/* */
options levelb

say "Length of René is" length("René")

say substr('1234567890','6',0,'')
say substr('1234567890','7',8,'.')


length: procedure = .int
  arg string1 = .string

substr: procedure = .string
arg string1 = .string, start=.int, length=.int, pad=.string
```

**Comment by adesutherland** [comment]
Weird :-(

I think substr() calls length() - are there two definitions of length()?

Can you post the rxas of the rexx program (just in case the compiler is
doing something stupid!

**Comment by rvjansen** [comment]
This is the version with length that does the padding wrong:
```
/*
 * cREXX COMPILER VERSION : cREXX-Phase-0 v0.1.6 + F0018
 * SOURCE                 : testsubstring
 * BUILT                  : 2021-09-10 17:41:12
 */

.globals=0

main() .locals=9 .expose=testsubstring.main
   * Line 3: say "Length of René is" length("René")
   * Line 3: length("René")
   load r1,1
   load r2,"René"
   call r3,length(),r1
   itos r3
   sconcat r2,"Length of René is",r3
   say r2
   * Line 5: say substr('1234567890','6',0,''
   * Line 5: substr('1234567890','6',0,''
   load r4,4
   load r5,"1234567890"
   load r6,6
   load r7,0
   itos r7
   load r8,""
   call r2,substr(),r4
   say r2
   * Line 6: say substr('1234567890','7',8,'.'
   * Line 6: substr('1234567890','7',8,'.'
   load r4,4
   load r5,"1234567890"
   load r6,7
   load r7,0
   itos r7
   load r8,"."
   call r1,substr(),r4
   say r1
   ret 0

length() .expose=global.length

substr() .expose=global.substr
```
This is the one without length() that gives the correct answer:
```
➜  rxasm git:(master) ✗ cat testsubstring.rxas
/*
 * cREXX COMPILER VERSION : cREXX-Phase-0 v0.1.6 + F0018
 * SOURCE                 : testsubstring
 * BUILT                  : 2021-09-10 17:43:40
 */

.globals=0

main() .locals=8 .expose=testsubstring.main
   * Line 5: say substr('1234567890','6',0,''
   * Line 5: substr('1234567890','6',0,''
   load r1,4
   load r2,"1234567890"
   load r3,6
   load r4,0
   load r5,""
   call r6,substr(),r1
   say r6
   * Line 6: say substr('1234567890','7',8,'.'
   * Line 6: substr('1234567890','7',8,'.'
   load r1,4
   load r2,"1234567890"
   load r3,7
   load r4,8
   load r5,"."
   call r7,substr(),r1
   say r7
   ret 0

substr() .expose=global.substr
```

**Comment by rvjansen** [comment]
one thing I see is that parameters are given as strings except for the 8 in length

**Comment by adesutherland** [comment]
Yes - it looks like the compiler is having a brainstorm

   * Line 5: substr('1234567890','6',0,''
   load r4,4
   load r5,"1234567890"
   load r6,6
   load r7,0
   itos r7
   load r8,""
   call r2,substr(),r4

r6 correctly is converted to an int 6 (from the string '6') by the optimiser
but r7,  why is it converting r7 to a string!

My random "stab in the dark" is that parameter 3 name "length" is interfering with the function name "length" - do you mind checking with a different parameter name e.g.

    substr: procedure = .string 
    arg string1 = .string, start=.int, **lengthxxx**=.int, pad=.string

Thanks!

PS. Again - this demonstrates the advantage of breaking out the stages - we can really see that the compiler is likely to be at fault (and not some caching in the register or whatever)

**Comment by adesutherland** [comment]
![image](https://user-images.githubusercontent.com/4367482/132950874-75bf141b-e423-4e54-9fbf-68bedf22bc5c.png)

You can see how the red (meaning procedure/function) LENGTH symbol on the bottom left is incorrectly linked to the length argument (on the far bottom right) befuddling the argument type checking logic (its kind of trying to convert an integer to a class of type LENGTH, and failing as that part of its brain does not exist!)

**Comment by adesutherland** [comment]
![image](https://user-images.githubusercontent.com/4367482/132953454-13d7022f-b69e-45f8-9dbd-4c947bdfd312.png)

I've pushed a fix for the symbol error (see above) and the compiler seems to be generating sane code - can you check if it fixes the error you found? Thks

**Comment by rvjansen** [comment]
fix works OK
