### ISSUE TITLE
Prefix Operators Need implementing

### ISSUE THREAD

**Issue by adesutherland** [adesutherland/CREXX#120]
### Discussed in https://github.com/adesutherland/CREXX/discussions/118

<div type='discussions-op-text'>

<sup>Originally posted by **Peter-Jacob** September 17, 2021</sup>
I have this rexx

```
/* test appendchar */
options levelb
v=-3.14
if v<0 then v=-v
```
it compiles to:

```
/*
 * cREXX COMPILER VERSION : cREXX-Phase-0 v0.1.6 + F0030
 * SOURCE                 : testabs
 * BUILT                  : 2021-09-17 10:37:25
 */

.globals=0

main() .locals=3 .expose=testabs.main
   * Line 2: v=-3.14
   load r1,-3.14
   * Line 3: {IF} v<0
   ilt r2,r1,0.0
   brf l15,r2
   * Line 3: {THEN}
   * Line 3: v=-v
   prefix_todo r1
l15:
   ret 0

```
The ilt r2,r1,0.0  should be a flt r2,r1,0.0  as it is a float and ilt picks up an integer.

I think the prefix_todo just marks not yet finished</div>

**Comment by adesutherland** [comment]
Work around: try v = 0 - v

**Comment by adesutherland** [comment]
Fixed in develop

**Comment by rvjansen** [comment]
works OK
