### ISSUE TITLE
please include instruction set architecture in binary releases

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#14]
My Ubuntu's are aarch64 (ARM-64). My mac is still X86-64 but will probably also ARM somewhere in the future. From the Ubuntu archive name I cannot see which one it is. I think even for Windows this is an issue (although I am not sure if there will be 32bit versions, or Windows for ARM (Surface) versions.

**Comment by adesutherland** [comment]
For the stage we are in it is all rough and ready! :-) I should be able to name the zipfiles quickly however.

Slightly long term - I think the best thing to do is agree the list of target architectures and I can (hopefully) make the binary pipeline build them all. What should we build for?

At the moment the code is only 64bit ...

**Comment by mgrossmann** [comment]
> What should we build for?

- MVS3.8J
- VM/370
- MacOS    x86-64bit & aarch64 
- Windows x86-64bit & aarch64
- Linux         x86-64bit & aarch64

**Comment by BobBolch** [comment]
Won't the first 2 be basically the same?
(I am assuming that MVS3.8J is 31 bit, but what do I know?)

Bob

**Comment by mgrossmann** [comment]
Hey Bob,


it depends on what we're talking about. When it comes to the implementation of the VM we have to look at VM and MVS differently. 

Or have I possibly misunderstood your question?


MIkeG

**Comment by mgrossmann** [comment]
I got it, you were all about the architecture of the instruction set. Yes, of course, VM and MVS are the same. Sorry

**Comment by rvjansen** [comment]
OS VS2 3.8 (MVS) is 24 bit.

René.

**Comment by rvjansen** [comment]
Yes, and I would like to be able to build for all existing versions; a 64 bit compiler for z/OS would be great stuff. Z/VM the same. But here we are talking ARCHLVLs. This will be a great hobby.

René.

**Comment by adesutherland** [comment]
We also need to target iOS and Android ...

**Comment by mgrossmann** [comment]
> We also need to target iOS and Android ...

I hope that was an April Fool's joke. :)

Should we create a WIKI page for our target platforms?

Would like to close this issue. :)

**Comment by rvjansen** [comment]
There is brexx for Android of course. Mark Hessling has a Regina IPA for IOS around. On my iPad I have ISH, which can run Regina and brexx and NetRexx locally, albeit in 32bit Linux versions. Let’s make wiki pages per target platform and close this.
