### ISSUE TITLE
Missing Do loop variants

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#147]
In my opinion a DO Forever is sufficient together with Leave and maybe iterate. Do until/while can then constructed with If statements

**Comment by adesutherland** [comment]
Rexx Loop constructs done including leave and iterate.
Added a BCF instruction (the partner to BCT)
Merged into develop and f0035
Hopefully not too many bugs!

**Comment by adesutherland** [comment]
The merge into f0035 seems to have failed - i'll fix after lunch

**Comment by adesutherland** [comment]
Merge fixed - however the next merge from develop will no doubt have a conflict :-(

**Comment by rvjansen** [comment]
opened items #178, 179, 180

**Comment by rvjansen** [comment]
Enhancement delivered, now in test.
