### ISSUE TITLE
please allow LOOP as a synonym for DO in loops 

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#177]
like ooRexx and NetRexx have

**Comment by Peter-Jacob** [comment]
for level b or level c?

**Comment by adesutherland** [comment]
I am happy to add it to b (and d?) - although personally I rather like the simplicity of DO!

**Comment by rvjansen** [comment]
it is my #1 error in Classic.

**Comment by adesutherland** [comment]
Is it correct that the LOOP keyword should NOT be used for non loops? I am assuming so!

**Comment by Peter-Jacob** [comment]
It's just available in do-loops-------- Ursprüngliche Nachricht --------Von: Adrian Sutherland ***@***.***>Datum: Mo., 1. Nov. 2021, 19:22An: adesutherland/CREXX ***@***.***>Cc: Peter-Jacob ***@***.***>, Comment ***@***.***>Betreff: Re: [adesutherland/CREXX] please allow LOOP as a synonym for DO in loops  (Issue #177)
Is it correct that the LOOP keyword should NOT be used for non loops? I am assuming so!

**Comment by rvjansen** [comment]
Yes, that is correct. It was introduced to lighten the overload on DO; when it is indicating a block scope, it is DO. When it loops, it is LOOP.

**Comment by adesutherland** [comment]
Implemented in develop and f0035

**Comment by rvjansen** [comment]
tested and working
