### ISSUE TITLE
DO FOR does not seem to work

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#178]
```
i=0
do for 10
i=i+1
end

Error @ 6:4 - #14.1, "for"
Error @ 8:1 - #10.1, "end"
2 error(s) in source file
```

**Comment by adesutherland** [comment]
I think I am following the ANSI standard

![image](https://user-images.githubusercontent.com/4367482/139594573-7ea10bee-8e82-478f-85f6-7b655e395dbe.png)

This tells me (but I might be wrong!!) that you can only have a FOR if you also have an assignment, so
```
do i=0 for 10 
```
is right.

BTW - at the moment cREXX will increment i (0,1,2 .... 9) - I am uncertain if this is right.

Of course
```
do 10 
```
should work

**Comment by rvjansen** [comment]
agree - got confused with NetRexx where this is valid syntax. Have corrected testcase.
