### ISSUE TITLE
non-initialised loop counter yields error #UPDATING_TAKEN_CONSTANT

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#179]
```
 /* test 2 */
j=0
do until i=15
i=i+1; j=j+1
end
if  i \= 15        then say 'failed in test          2 '
if  j \= 15        then say 'failed in test          2 '
```

```
rxc loop
Error @ 17:1 - #UPDATING_TAKEN_CONSTANT, "i"
1 error(s) in source file
```

**Comment by adesutherland** [comment]
I think this is as designed for level b at least?! i has not got a value so "I" + 1 will fail anyway

**Comment by Peter-Jacob** [comment]
In my opinion, a correct behaviour. The UNTIL  works at the END statement, so i=i+1 is firstly executed, and it's not set.

**Comment by adesutherland** [comment]
> In my opinion, a correct behaviour. The UNTIL works at the END statement, so i=i+1 is firstly executed, and it's not set.

Moreover, the i=15 is a boolean expression NOT an assignment ...

**Comment by rvjansen** [comment]
agree
