### ISSUE TITLE
Loop TO check is not right for a negative BY value

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#180]
```
/* test 7 */
  j=0;i=0
  do i=0-1 to(10-22)by 20-22 until i<-7
    j=j+1; end
say i j
```
should say -9 5
now says -1 0

**Comment by rvjansen** [comment]
checked in tests/loop.rexx in F0035

**Comment by Peter-Jacob** [comment]
I think DO until is not implemented in levelb. Didn't we just agree on do forever as additionally do variant?
```
* Line 3: {DO}
   * Line 3: i=0-1
   load r2,-1
   * Line 3: to(10-22)
   load r3,-12
   * Line 3: by 20-22 until i<-7
   itos r2
   sconcat r4,"-2 UNTIL",r2
   slt r4,r4,"-7"
...
```

**Comment by adesutherland** [comment]
do until is implemented (but that is not saying there is not a bug!)
```
/* rexx */
options levelb
i = 9
do until i<10
say "until" i
end

do while i>10
say "while" i
end
```

says

```
until 9
```

because the while test is done first etc,

**Comment by adesutherland** [comment]
I have to say Rene - these are mean tests :-)

Peter - the "slt" is weird! Let me investigate!

**Comment by adesutherland** [comment]
Peter I get

```
/*
 * cREXX COMPILER VERSION : cREXX F0037
 * SOURCE                 : scratch
 * BUILT                  : 2021-10-31 17:04:39
 */

.globals=0

main() .locals=6 .expose=scratch.main
   * Line 5: j=0
   load r1,0
   * Line 5: i=0
   load r2,0
   * Line 6: {DO}
   * Line 6: i=0-1
   load r2,-1
   * Line 6: to(10-22)
   load r3,-12
   * Line 6: by 20-22
   load r4,-2
l35dostart:
   * Line 6: to(10-22)
   igt r0,r2,r3
   brt l35doend,r0
   * Line 7: j=j+1
   iadd r1,r1,1
l35doinc:
   * Line 6: until i<-7
   ilt r5,r2,-7
   brt l35doend,r5
   * Line 6: by 20-22
   iadd r2,r4,r2
   * Line 6: {DO-END}
   br l35dostart
l35doend:
   * Line 8: say i j
   itos r2
   itos r1
   sconcat r5,r2,r1
   say r5
   * Line 8: 
   ret 0
```

**Comment by adesutherland** [comment]
This is the bug
```
ilt r5,r2,-7
```
it should be 'igt' because the BY value <0 - laziness on my part!

**Comment by rvjansen** [comment]
Sorry about that ;-)
More to come however.

René.

**Comment by Peter-Jacob** [comment]
@adesutherland I didn't run a BUILD after fetching from GIT. After doing it, compile looks ok.

**Comment by Peter-Jacob** [comment]
> This is the bug
> 
> ```
> ilt r5,r2,-7
> ```
> 
> it should be 'igt' because the BY value <0 - laziness on my part!

I wouldn't call your laziness "laziness"! lazy people don't contribute and therefore make no errors.

**Comment by adesutherland** [comment]
I am working in this now. One thing surprised me from the ansi spec

> if \\#Contains(do_specification,byexpr) then
> #By.#Loop = 1
> end

(buried on the top of page 81 on the free draft version)

This means that if BY is not specified it is 1, and

     for i = 10 to 1 

won't automatically set by to -1 - which is probably quite right and safer - and makes the fix easier!

**Comment by adesutherland** [comment]
Fixed in develop and f0035

**Comment by rvjansen** [comment]
tested and working
