### ISSUE TITLE
D2X BIF assembly fails with invalid IREM instruction in f0035

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#181]
merge or checkin problem ? I thought this one worked previously

**Comment by adesutherland** [comment]
:-(

I hope I haven't completely messed up f0035!

**Comment by adesutherland** [comment]
We renamed the instruction IREM to IMOD. I don't think we changes the assembly BIF perhaps?

**Comment by Peter-Jacob** [comment]
D2X
My fault, IREM was changed to IMOD, and I didn't change the BIF accordingly. 
I fixed the problem: commit 9acaa3e782cc6dda18f675d4cb5b972c5b4b6ed1 

If your test rexx contains more than just D2X, they may fail, as we have a problem with a looping RXC. 

Please test D2X and close if fixed

**Comment by rvjansen** [comment]
working.
