### ISSUE TITLE
rxc _datei fails 

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#184]
great, but now:
rxc _datei
Error @ 70:42 - #31.1, "idateJ"
1 error(s) in source file

_Originally posted by @rvjansen in https://github.com/adesutherland/CREXX/discussions/175#discussioncomment-1569137_

**Comment by Peter-Jacob** [comment]
confirm error, has been fixed: commit cb7fc1cd58ee432da8d8e7e843f67ffe19d9c0e4
please test and close issue.

**Comment by rvjansen** [comment]
fixed.
