### ISSUE TITLE
Lost code for bitwise instructions  

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#188]
I started with coding for c2x and realised all my coding for bitwise instructions have been lost:
   commit b1d9847c2d804a4ee7989959bbac40e13b7647b1
   commit a7d20c6787a25d2c0710a468890f47b7b183083b
I manually recovered the code lines, as I didn't know if there is an automatic way. 

It's strange, I have no idea how this happened and I hope there is no more vanished.

**Comment by rvjansen** [comment]
I can get them back easy - will do that tonight. Might be a cleanup mishap when deleting the rxas of which the source was in the rexx directory. If so, mea culpa. But I will restore.

**Comment by Peter-Jacob** [comment]
I recovered my coding, maybe you can check if more is lost. I don't blame anyone, in the end, it turns out, I was it.

**Comment by adesutherland** [comment]
I hope I didn't lose them when I was doing a merge?!

Probably worth finding out what went wrong for any lessons learned ...

**Comment by rvjansen** [comment]
Most important message here is, that everything is recoverable in git.

René.

**Comment by adesutherland** [comment]
The merge i did in the 29/10 seems to be the fault - I will review now to see what I deleted

A

**Comment by adesutherland** [comment]
@Peter-Jacob 

This is what was lost - have you recreated?

```
/* ------------------------------------------------------------------------------------
  *  IOR_REG_REG_REG bitwise OR (op1=op2|op3)                           pej 17 Oct 2021
  *  -----------------------------------------------------------------------------------
  */
        START_INSTRUCTION(IOR_REG_REG_REG) CALC_DISPATCH(3);
            DEBUG("TRACE - IOR R%d,R%d,%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)REG_IDX(3));
            REG_RETURN_INT(op2RI | op3RI);
            DISPATCH;
/* -----------------------------------------------------------------------------------
 *  IOR_REG_REG_INT  bitwise OR (op1=op2|op3)                          pej 17 Oct 2021
 *  ----------------------------------------------------------------------------------
 */
        START_INSTRUCTION(IOR_REG_REG_INT) CALC_DISPATCH(3);
            DEBUG("TRACE - IOR R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)op3I);
            REG_RETURN_INT(op2RI | op3I);
            DISPATCH;

/* ------------------------------------------------------------------------------------
 *  IAND_REG_REG_INT  bitwise AND (op1=op2&op3)                         pej 17 Oct 2021
 *  -----------------------------------------------------------------------------------
 */
        START_INSTRUCTION(IAND_REG_REG_INT) CALC_DISPATCH(3);
            DEBUG("TRACE - IAND R%d,R%d,%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)op3I);
            REG_RETURN_INT(op2RI & op3I);
            DISPATCH;
/* -----------------------------------------------------------------------------------
 *  IAND_REG_REG_REG  bitwise AND (op1=op2&op3)                        pej 17 Oct 2021
 *  ----------------------------------------------------------------------------------
 */
        START_INSTRUCTION(IAND_REG_REG_REG) CALC_DISPATCH(3);
            DEBUG("TRACE - IAND R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)REG_IDX(3));
            REG_RETURN_INT(op2RI & op3RI);
            DISPATCH;

/* -----------------------------------------------------------------------------------
 *  IXOR_REG_REG_REG  bitwise XOR (op1=op2^op3)                        pej 17 Oct 2021
 *  ----------------------------------------------------------------------------------
 */
        START_INSTRUCTION(IXOR_REG_REG_REG) CALC_DISPATCH(3);
            DEBUG("TRACE - IXOR R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)REG_IDX(3));
            REG_RETURN_INT(op2RI ^ op3RI);
            DISPATCH;

/* -----------------------------------------------------------------------------------
 *  IXOR_REG_REG_INT  bitwise XOR (op1=op2^op3)                        pej 17 Oct 2021
 *  ----------------------------------------------------------------------------------
 */
        START_INSTRUCTION(IXOR_REG_REG_INT) CALC_DISPATCH(3);
            DEBUG("TRACE - IXOR R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)op3I);
            REG_RETURN_INT(op2RI ^ op3I);
            DISPATCH;

/* -----------------------------------------------------------------------------------
 *  ISHL_REG_REG_REG  bitwise shift logical left (op1=op2<<op3)         pej 17 Oct 2021
 *  ----------------------------------------------------------------------------------
 */
        START_INSTRUCTION(ISHL_REG_REG_REG) CALC_DISPATCH(3);
            DEBUG("TRACE - ISHL R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)REG_IDX(3));
            REG_RETURN_INT(op2RI << op3RI);
            DISPATCH;

/* -----------------------------------------------------------------------------------
 *  ISHL_REG_REG_INT  bitwise shift logical left (op1=op2<<op3)         pej 17 Oct 2021
 *  ----------------------------------------------------------------------------------
 */
        START_INSTRUCTION(ISHL_REG_REG_INT) CALC_DISPATCH(3);
            DEBUG("TRACE - ISHL R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)op3I);
            REG_RETURN_INT(op2RI << op3I);
            DISPATCH;
/* -----------------------------------------------------------------------------------
 *  ISHR_REG_REG_REG  bitwise shift logical right (op1=op2>>op3)       pej 17 Oct 2021
 *  ----------------------------------------------------------------------------------
 */
        START_INSTRUCTION(ISHR_REG_REG_REG) CALC_DISPATCH(3);
            DEBUG("TRACE - ISHR R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)REG_IDX(3));
            REG_RETURN_INT(op2RI >> op3RI);
            DISPATCH;

/* -----------------------------------------------------------------------------------
 *  ISHR_REG_REG_INT  bitwise shift logical right (op1=op2>>op3)       pej 17 Oct 2021
 *  ----------------------------------------------------------------------------------
 */
        START_INSTRUCTION(ISHR_REG_REG_INT) CALC_DISPATCH(3);
            DEBUG("TRACE - IXSHL R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)op3I);
            REG_RETURN_INT(op2RI >> op3I);
            DISPATCH;
/* -----------------------------------------------------------------------------------
 *  INOT_REG_REG  inverts all bits of an integer (op1=~op2)            pej 17 Oct 2021
 *  ----------------------------------------------------------------------------------
 */
        START_INSTRUCTION(INOT_REG_REG) CALC_DISPATCH(2);
            DEBUG("TRACE - INOT R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2));
            REG_RETURN_INT(~op2RI);
            DISPATCH;

/* -----------------------------------------------------------------------------------
 *  INOT_REG_INT  inverts all bits of an integer (op1=~op2)            pej 17 Oct 2021
 *  ----------------------------------------------------------------------------------
 */
        START_INSTRUCTION(INOT_REG_INT) CALC_DISPATCH(2);
            DEBUG("TRACE - INOT R%d,R%d,R%d\n", (int)REG_IDX(1), (int)op2I);
            REG_RETURN_INT(~op2I);
            DISPATCH;
```

**Comment by adesutherland** [comment]
I think this was the merge when we had both changed irem to imod. I think the lessons are:

1/ We desperately need the regression tests to run on each build
2/ After a troublesome merge (we knew this was tricky) it needs a careful review by all parties

Anything else?

**Comment by Peter-Jacob** [comment]
@adesutherland yr 1/ For every commit in BREXX370 we automatically run tests with all test cases (adopted from the tests @rvjansen is using) and create a summarised return code. we maybe need to implement something similar to CREXX

**Comment by Peter-Jacob** [comment]
> @Peter-Jacob
> 
> This is what was lost - have you recreated?
> 
> ```
> /* ------------------------------------------------------------------------------------
>   *  IOR_REG_REG_REG bitwise OR (op1=op2|op3)                           pej 17 Oct 2021
>   *  -----------------------------------------------------------------------------------
>   */
>         START_INSTRUCTION(IOR_REG_REG_REG) CALC_DISPATCH(3);
>             DEBUG("TRACE - IOR R%d,R%d,%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)REG_IDX(3));
>             REG_RETURN_INT(op2RI | op3RI);
>             DISPATCH;
> /* -----------------------------------------------------------------------------------
>  *  IOR_REG_REG_INT  bitwise OR (op1=op2|op3)                          pej 17 Oct 2021
>  *  ----------------------------------------------------------------------------------
>  */
>         START_INSTRUCTION(IOR_REG_REG_INT) CALC_DISPATCH(3);
>             DEBUG("TRACE - IOR R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)op3I);
>             REG_RETURN_INT(op2RI | op3I);
>             DISPATCH;
> 
> /* ------------------------------------------------------------------------------------
>  *  IAND_REG_REG_INT  bitwise AND (op1=op2&op3)                         pej 17 Oct 2021
>  *  -----------------------------------------------------------------------------------
>  */
>         START_INSTRUCTION(IAND_REG_REG_INT) CALC_DISPATCH(3);
>             DEBUG("TRACE - IAND R%d,R%d,%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)op3I);
>             REG_RETURN_INT(op2RI & op3I);
>             DISPATCH;
> /* -----------------------------------------------------------------------------------
>  *  IAND_REG_REG_REG  bitwise AND (op1=op2&op3)                        pej 17 Oct 2021
>  *  ----------------------------------------------------------------------------------
>  */
>         START_INSTRUCTION(IAND_REG_REG_REG) CALC_DISPATCH(3);
>             DEBUG("TRACE - IAND R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)REG_IDX(3));
>             REG_RETURN_INT(op2RI & op3RI);
>             DISPATCH;
> 
> /* -----------------------------------------------------------------------------------
>  *  IXOR_REG_REG_REG  bitwise XOR (op1=op2^op3)                        pej 17 Oct 2021
>  *  ----------------------------------------------------------------------------------
>  */
>         START_INSTRUCTION(IXOR_REG_REG_REG) CALC_DISPATCH(3);
>             DEBUG("TRACE - IXOR R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)REG_IDX(3));
>             REG_RETURN_INT(op2RI ^ op3RI);
>             DISPATCH;
> 
> /* -----------------------------------------------------------------------------------
>  *  IXOR_REG_REG_INT  bitwise XOR (op1=op2^op3)                        pej 17 Oct 2021
>  *  ----------------------------------------------------------------------------------
>  */
>         START_INSTRUCTION(IXOR_REG_REG_INT) CALC_DISPATCH(3);
>             DEBUG("TRACE - IXOR R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)op3I);
>             REG_RETURN_INT(op2RI ^ op3I);
>             DISPATCH;
> 
> /* -----------------------------------------------------------------------------------
>  *  ISHL_REG_REG_REG  bitwise shift logical left (op1=op2<<op3)         pej 17 Oct 2021
>  *  ----------------------------------------------------------------------------------
>  */
>         START_INSTRUCTION(ISHL_REG_REG_REG) CALC_DISPATCH(3);
>             DEBUG("TRACE - ISHL R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)REG_IDX(3));
>             REG_RETURN_INT(op2RI << op3RI);
>             DISPATCH;
> 
> /* -----------------------------------------------------------------------------------
>  *  ISHL_REG_REG_INT  bitwise shift logical left (op1=op2<<op3)         pej 17 Oct 2021
>  *  ----------------------------------------------------------------------------------
>  */
>         START_INSTRUCTION(ISHL_REG_REG_INT) CALC_DISPATCH(3);
>             DEBUG("TRACE - ISHL R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)op3I);
>             REG_RETURN_INT(op2RI << op3I);
>             DISPATCH;
> /* -----------------------------------------------------------------------------------
>  *  ISHR_REG_REG_REG  bitwise shift logical right (op1=op2>>op3)       pej 17 Oct 2021
>  *  ----------------------------------------------------------------------------------
>  */
>         START_INSTRUCTION(ISHR_REG_REG_REG) CALC_DISPATCH(3);
>             DEBUG("TRACE - ISHR R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)REG_IDX(3));
>             REG_RETURN_INT(op2RI >> op3RI);
>             DISPATCH;
> 
> /* -----------------------------------------------------------------------------------
>  *  ISHR_REG_REG_INT  bitwise shift logical right (op1=op2>>op3)       pej 17 Oct 2021
>  *  ----------------------------------------------------------------------------------
>  */
>         START_INSTRUCTION(ISHR_REG_REG_INT) CALC_DISPATCH(3);
>             DEBUG("TRACE - IXSHL R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2), (int)op3I);
>             REG_RETURN_INT(op2RI >> op3I);
>             DISPATCH;
> /* -----------------------------------------------------------------------------------
>  *  INOT_REG_REG  inverts all bits of an integer (op1=~op2)            pej 17 Oct 2021
>  *  ----------------------------------------------------------------------------------
>  */
>         START_INSTRUCTION(INOT_REG_REG) CALC_DISPATCH(2);
>             DEBUG("TRACE - INOT R%d,R%d,R%d\n", (int)REG_IDX(1), (int)REG_IDX(2));
>             REG_RETURN_INT(~op2RI);
>             DISPATCH;
> 
> /* -----------------------------------------------------------------------------------
>  *  INOT_REG_INT  inverts all bits of an integer (op1=~op2)            pej 17 Oct 2021
>  *  ----------------------------------------------------------------------------------
>  */
>         START_INSTRUCTION(INOT_REG_INT) CALC_DISPATCH(2);
>             DEBUG("TRACE - INOT R%d,R%d,R%d\n", (int)REG_IDX(1), (int)op2I);
>             REG_RETURN_INT(~op2I);
>             DISPATCH;
> ```

yes, it is re-created and will be getting into the next commit.

**Comment by rvjansen** [comment]
We are already building develop on Jenkins, and I will add the unit tests and make sure I will get a message when they fail.

René.

**Comment by rvjansen** [comment]
seems to be recovered and can be closed
