### ISSUE TITLE
strip BIF does not compile

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#196]
rxc strip
Error @ 37:17 - #INVALID_ASSEMBLER, "begin"
Error @ 38:22 - #49.3, ","
Error @ 40:7 - #49.4, "assembler end"
Error @ 40:17 - #49.3, "end"
4 error(s) in source file
rxas strip
Can't open input file
make: *** [strip.rxbin] Error 255

**Comment by rvjansen** [comment]
I checked in a provisional fix; please check

**Comment by Peter-Jacob** [comment]
thanks, I additionally removed an ITOS instruction, which is not needed. New version is in commit e7935f35232cdacc5ab6481f9d14a32083b1f920. Please verify and close if solved.

**Comment by rvjansen** [comment]
works as designed
