### ISSUE TITLE
x2b fails all testcases

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#214]
Look for X2B OK
failed in test 1
failed in test 2
hex string contains invalid character 1 C1
failed in test 3
failed in test 4
failed in test 5
failed in test 6
failed in test 7
failed in test 8
hex string contains invalid character 1 02 03
failed in test 9
hex string contains invalid character 102 03
failed in test 10
failed in test 11
hex string contains invalid character 11 2F
failed in test 12
X2

**Comment by Peter-Jacob** [comment]
Errors corrected, except test case 4: we don't support the 'C3'x notation in levelb, this must be tested with classic rexx. Please verify t and close. Changed modules in commit 449f9a55d3d59fc9bc53a084588f5ad531d1bb91

**Comment by rvjansen** [comment]
X2B except testcase 4 tests OK. Commented out testcase 4 until level c is alive.
