### ISSUE TITLE
hex string contains invalid character

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#215]
not all hex strings parse correctly
like for example the cases in ts_x2b

**Comment by Peter-Jacob** [comment]
this is true, "01 02 ff" was not permitted. I changed this - hopefully consistently, with the last commit.

**Comment by Peter-Jacob** [comment]
commit f73543e31e98157229791102de738a7ea3fad7fa modified test case 4 and removed 'nn'x notation. The function uses a relaxed version of hex parsing allowing blanks as separator chars.  Please verify and close the issue.

**Comment by rvjansen** [comment]
verified and closed
