### ISSUE TITLE
d2c fails all testcases

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#217]
Look for D2C OK
failed in test 1
failed in test 2
failed in test 3
failed in test 4
failed in test 5
failed in test 6
failed in test 7
failed in test 8
failed in test 9
failed in test 10
failed in test 11
failed in test 12
failed in test 13
failed in test 14
failed in test 15
failed in test 16
failed in test 17
failed in test 18
failed in test 19
failed in test 20
failed in test 21
failed in test 22
failed in test 23
failed in test 24
failed in test 25

**Comment by Peter-Jacob** [comment]
All test cases use the 'nn'X not available in level b. I try to set up an alternative way to test them, as I found some misbehaviour.
I will try this:
`  if c2x(d2c(nn))    \= 'hex-value'  then say 'failed in test` 2 '

**Comment by Peter-Jacob** [comment]
corrected several errors: commit 2dd584fea2b2bffeeb50d51d13a33188d4898aa6. TS_D2C contains a modified version of the tests. After converting D2C it's converted via C2X into the hex-value and then compared to the 'hex-value' instead the binary value. The final test must be performed with classic REXX. Please verify the changes and close the issue (temporarily).

**Comment by rvjansen** [comment]
with modifications, works. Needs version for level C.
