### ISSUE TITLE
we have to implement TRACE in the bifs

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#230]
I assume that we won't have to check at runtime, because we have a compiler. So we probably can have a switch to include TRACE code only when needed.

**Comment by adesutherland** [comment]
Noted! I have a rough design already :-) https://github.com/adesutherland/CREXX/wiki/REXX-Assembler-(RXAS)#code-annotation-and-debug-pool

**Comment by Peter-Jacob** [comment]
a trace in level b would be awesome!

**Comment by rvjansen** [comment]
I just wonder: will the generic trace facility that the compiler will implement be enough, or do we need an extra facility in the bifs to enable tracing with more knowledge that the bifs only might have - hard to come up with examples here, but I just have a hunch this might be the case. Well, for example entry- and exit- arguments. Will there (or is there) be a mechanism in which a bif can ask some control block whether we are tracing or not?

I ask because when we have compiled bifs, we otherwise need a version with trace enabled and one without, and then when we look at the possible combinations of trace options, several. Or maybe just have trace-enabled versions for the implementors, and switch them on in the debug version of the translator?

**Comment by adesutherland** [comment]
Teaser - This is the first hint of trace ... and importantly when breakpoints are off then performance seems unaffected :-)

```
Starting inst# scratch-0x0
TRACE - BPON   <- This instruction enables breakpoints
BREAKPOINT CHECK  <- This is where we will check if a breakpoint has been reached
TRACE - LOAD R1,1
BREAKPOINT CHECK
TRACE - LOAD R2,3
BREAKPOINT CHECK
TRACE - IGT R0,R1,R2
BREAKPOINT CHECK
TRACE - BRT 0x17,R0
BREAKPOINT CHECK
TRACE - ITOS R1
BREAKPOINT CHECK
TRACE - SAY R1
1
BREAKPOINT CHECK
TRACE - BPOFF   <- Disables Breakpoints
TRACE - INC R1   <- Note that there are no more BREAKPOINT CHECKS
TRACE - BR 0x7
TRACE - IGT R0,R1,R2
TRACE - BRT 0x17,R0
TRACE - ITOS R1
TRACE - SAY R1
2
TRACE - BPOFF
TRACE - INC R1
TRACE - BR 0x7
TRACE - IGT R0,R1,R2
TRACE - BRT 0x17,R0
TRACE - ITOS R1
TRACE - SAY R1
```

**Comment by rvjansen** [comment]
closing as this will be in the breakpoint/tracing system and not in individual bifs
