### ISSUE TITLE
date('wednews') returns 29 11 2021 instead of Monday 

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#236]
I admit this is a kinda spurious testcase, but date('wednews') should return the day of the week in English

**Comment by Peter-Jacob** [comment]
solved with commit 1eeafd5a603f9f0d88872ae1661943bcd3ede189
Please run a full date check, as I had to relocate some of the coding.

If fixed version works please close issue.

**Comment by rvjansen** [comment]
works
