### ISSUE TITLE
date() bif implementation misses argument 4, separator

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#237]
```
say ''
say 'with separators specified'
say "date('s','716308','b','/')   ==> 1962/03/10  :" date('s','716308','b','/')
say "date('s','716308','b','-')   ==> 1962-03-10  :" date('s','716308','b','-')
say "date('w',7688,'c')           ==> Sunday      :" date('w',7688,'c')
say "date('c','1 Feb 2021')       ==> 7703        :" date('c','1 Feb 2021')
say "date('J','18 Jan 2021')      ==> 2021018     :" date('j','18 Jan 2021')
say "date('J','10 Mar 1962')      ==> 1962069     :" date('j','10 Mar 1962')

date: Procedure = .string
   arg iFormat = "", idate = "", oFormat = "",  oSep = ""
```
(I added that last argument in uncertain hope)

gives me:
```
with separators specified
date('s','716308','b','/')   ==> 1962/03/10  : 19620310
date('s','716308','b','-')   ==> 1962-03-10  : 19620310


TRACE - Signal Received - aborting
➜  tests_functional git:(feature/f0035) ✗
```

**Comment by Peter-Jacob** [comment]
Is this an enhancement? I couldn't find the fourth parameter in the various REXX documentation I have.
Anyway, it is a good idea and not too hard to implement.

**Comment by Peter-Jacob** [comment]
if we use separators other than the standard ones, it might be difficult to remove them if presented in an input format.
E.g. 31/12/21 is European format if we use DATE('E',,,'-') the date becomes 31-12-21. Do we want to present this date also as an input format? This would actually require a fifth separator parameter:
  DATE('USA',"31-12-21",":","-")   
                                        x   x    ---- input seperator
                                        x   -------- output seperator.

**Comment by rvjansen** [comment]
e.g. from z/VM 7.1 Rexx Reference
![Screenshot 2021-11-30 at 11 56 33](https://user-images.githubusercontent.com/12018881/144081726-2c639853-bdb1-4252-903a-ee077cb0ef6c.png)
:

**Comment by rvjansen** [comment]
https://www.ibm.com/docs/en/zvm/7.2?topic=functions-date

**Comment by rvjansen** [comment]
for compatibility we also have to look at this:
The first call to DATE or TIME in one clause causes a time stamp to be made that is then used for all calls to these functions in that clause. Therefore, multiple calls to any of the DATE or TIME functions or both in a single expression or clause are guaranteed to be consistent with each other.

I was discussing DATE() with Mike C. during the symposium, and asked why some of the options were dropped from the standard. Also, he thinks we should not add extra options to standard DATE() - in his view e.g. a LOCALDATE() function should cater for the extra options.

**Comment by Peter-Jacob** [comment]
Astounding! I looked at https://www.ibm.com/docs/en/zos/2.1.0?topic=functions-date, there are no separator clauses. So VM has a richer functionality.
With extra options, you mean taking advantage of different time zones, not the separator stuff, don't you?
I'll start now with the 2 separators, I'll let you how I progress.

**Comment by Peter-Jacob** [comment]
the 2 separator parms are added commit 2580020a14dee6c953be150f077602d1eda3f0da.

Syntax  Date(o-format,date,iformat,o-separator,i-separator)

The separator parms are only used with an appropriate format. They default to "/" for European and USA formats, and "." in German formats

**Comment by rvjansen** [comment]
lib/rxfns/tests_functional/ts_date2.rexx now segfaults on the first function

**Comment by Peter-Jacob** [comment]
The data prototype statement is incomplete! It must be:
```
/* Prototype functions */
date: Procedure = .string
   arg iFormat = "", idate = "", oFormat = "", osep="", isep=""
```
I committed an updated version:  4636664e48f714fecf2161020f3bb8b2abb2f6d8

**Comment by rvjansen** [comment]
works as designed
