### ISSUE TITLE
prime_string for floats  

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#24]
Wouldn't it be better to drop the trailing zeros for float to string conversion?
currently used in prime_string: 
      snprintf(v->string_value,SMALL_STRING_BUFFER,"%f",v->float_value);     by replacing it with
      snprintf(v->string_value,SMALL_STRING_BUFFER,"%g",v->float_value);
the trailing zeros can be removed.

**Comment by adesutherland** [comment]
I agree

**Comment by Peter-Jacob** [comment]
tx, will change the code accordingly
