### ISSUE TITLE
inconsistencies in operands.c

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#25]
It seems operands.c contains inconsistencies:

   instr_f("fmult", "Float Multiply (op1=op2*op3)", OP_REG, OP_REG, OP_REG);
   instr_f("fmult", "Float Multiply (op1=op2*op3)", OP_REG, OP_REG, OP_FLOAT);
doesn't allow a OP_REG,OP_FLOAT,OP_REG
whereas it is allowed in fdiv:
   instr_f("fdiv", "Float Divide (op1=op2/op3)", OP_REG, OP_REG, OP_REG);
   instr_f("fdiv", "Float Divide (op1=op2/op3)", OP_REG, OP_REG, OP_FLOAT);
   instr_f("fdiv", "Float Divide (op1=op2/op3)", OP_REG, OP_FLOAT, OP_REG);
is this wanted? 

There are several other operations, which also allow just 2 of 3 variants.

**Comment by adesutherland** [comment]
There was logic in my madness! I was trying to reduce the number of instructions

So if the compiler wants to use

    fmult reg, float, reg 

it can always re-write to

    fmult reg, reg, float

However for idiv (and isub) you can't reverse the operands!

That all said - I am very happy if you want to add the "missing" instructions, for logical completeness

**Comment by Peter-Jacob** [comment]
It makes sense to add just those missing operations which can't be fixed by the compiler. I will handle extensions In the light of this
