### ISSUE TITLE
F0038: Translate BIF erorrs

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#256]
New tests for TRANSLATE fail in a number of cases:
```
TRANSLATE failed in test 22: translate('abcdef ',,,'$')  'ABCDEF ' but must be '$$$$$$$'
TRANSLATE failed in test 23: translate(ABCDEF ,1e+17,AC,1)  '1bedef ' but must be '1bEdef '
TRANSLATE failed in test 24: translate(ABCDEF ,1e+17,AC,1)  '1bedef ' but must be '1bEdef '
TRANSLATE failed in test 28: TRANSLATE(APQRV, ,PR) 'A?Q?V' but must be 'A Q V'
```

**Comment by Peter-Jacob** [comment]
next on my list!

**Comment by Peter-Jacob** [comment]
I would agree, if the tests look like this:
TRANSLATE failed in test 23: translate(ABCDEF ,1e+17,AC,1)  '1bedef ' but must be '1bEdef '
TRANSLATE failed in test 24: translate(ABCDEF ,1e+17,AC,1)  '1bedef ' but must be '1bEdef '

but in TS_TRANSLATE they look like this:
```
if translate('abcdef ',1e+17,'ac','1') \= '1bEdef ' then do
  errors=errors+1
  say 'TRANSLATE failed in test 23: translate('abcdef ',1e+17,'ac','1') ' "'"translate('abcdef ',1e+17,'ac','1')"'" "but must be '1bEdef '"
end

if translate('abcdef ',1e+17,'ac','1') \= '1bEdef ' then do
  errors=errors+1
  say 'TRANSLATE failed in test 24: translate('abcdef ',1e+17,'ac','1') ' "'"translate('abcdef ',1e+17,'ac','1')"'" "but must be '1bEdef '"
end
```
with lower case source strings

**Comment by Peter-Jacob** [comment]
ok, I understand the problem: if the string is not coded within quotes, it is regarded as "variable" and translated to a lower case string. This seems to be a behaviour of the compiler and has nothing to do with the TRANSLATE bif

**Comment by rvjansen** [comment]
Well, then we can assign it to Adrian. Or try to understand how that works!

René.

**Comment by Peter-Jacob** [comment]
Errors corrected, except the ones caused by unquoted strings: commit ec9ec09270529cdea1e2504df3d68b06f0cc2d79. Please verify.

**Comment by adesutherland** [comment]
It's weird that you say it is converted to lowercase - anyway I will check!

**Comment by Peter-Jacob** [comment]
I was wrong, the assembly looks good!
```
main() .locals=7 .expose=ts_test.main
   * Line 2: say translate(ABCDEF,1e+17,'ac','1') \= '1bEdef '
   * Line 2: translate(ABCDEF,1e+17,'ac','1')
   load r1,4
   load r2,"ABCDEF"
   settp r2,0
   load r3,"1e+17"
   settp r3,3
   load r4,"ac"
   settp r4,3
   load r5,"1"
   settp r5,3
   call r6,translate(),r1
   sne r6,r6,"1bEdef "
   itos r6
   say r6
   * Line 3: return
   ret 0

```
I'll re-think!

**Comment by Peter-Jacob** [comment]
I ran it standalone:
`say translate(ABCDEF,1e+17,'ac','1') "\= '1bEdef '"`
and got 
`ABCDEF \= '1bEdef '`
There was no translation actioned, as the from-character string doesn't have a match with the original string. I think this is correct. Do I miss something?

**Comment by rvjansen** [comment]
I ran them on z/VM 7.2 and got other answers than the test cases. Closing this issue and will re-open when I have more clarity about these corner cases.
