### ISSUE TITLE
please remove ssay from the rexx assembler instruction set

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#257]
seems better to do that now, as we do not have any legacy depending on it

**Comment by adesutherland** [comment]
I have marked quite a few instructions as depreciated, and there are still some (but only a few) unimplemented instructions.

I would like to clean out all the depreciated ones and got rid of the unimplemented one (we can then get rid of the missing instructions generated stub file) in f0031.

@Peter-Jacob @rvjansen - any issues with doing this? Might break some assembler programs ...

**Comment by rvjansen** [comment]
Yes, those programs that need to be broken. From my point of view, please go ahead.

René.

**Comment by Peter-Jacob** [comment]
Is this done? I could remove them in f0038.

**Comment by Peter-Jacob** [comment]
SSAY remmoved: commit 28895b2c73595b8f18daf58d53bd67c49451ea35

**Comment by rvjansen** [comment]
excellent.
