### ISSUE TITLE
F0038: need RANDOM BIF

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#263]

**Comment by rvjansen** [comment]
I think a microcode instruction would be the best fit here: C has rand() and srand().

**Comment by Peter-Jacob** [comment]
in progress, ready by tomorrow - I hope.

**Comment by Peter-Jacob** [comment]
The REXX standard seems to have a default of RANDOM(0,999, seed). In my eyes, a strange default shall we pursue with it?

**Comment by rvjansen** [comment]
I think we will have to, hard to call it Rexx if we don’t?

**Comment by Peter-Jacob** [comment]
new IRAND instruction and the new RANDOM.REXX BIF added, also a simple TS_RANDOM.REXX. Commit 1d1f3e52ebccece8cd37204d362684cbe50ae9cc 
Please test!
btw: I used the RAISE function, I am not sure about the error numbering.

**Comment by rvjansen** [comment]
I cannot find it!

**Comment by Peter-Jacob** [comment]
it's on f0038: commit 1d1f3e52ebccece8cd37204d362684cbe50ae9cc  the hyperlink refers to it.

**Comment by rvjansen** [comment]
Now we have an explanation about how I missed this in the merge, I am still missing the commented-out (by me, it misses variables that I cannot conjure up from somewhere) irand and srand instructions in branch feature/f0038

**Comment by rvjansen** [comment]
or, becaus the BIF is there, let me close this issue.
