### ISSUE TITLE
Random BIF doesn't compile

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#272]
There is a new commit 5e26f6d93df759cd14774d404f12b77a675318c4 which should solve the compile problem of the IRAND instruction. Please verify and let me know if it works.   
Warning: rxvmintp.c contains the new OPENDLL instruction which is windows-only right now. It's enclosed in ifdef win32, and shouldn't bother other OSes.

**Comment by rvjansen** [comment]
it works.
