### ISSUE TITLE
Problems after adding new instruction

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#285]
In preparation for the dynamic dll call, I added a new instruction to retrieve the dll parms dynamically. A build project smashed my system again:

```
====================[ Build | all | Debug ]=====================================
"C:\Program Files\JetBrains\CLion 2020.2.4\bin\cmake\win\bin\cmake.exe" --build C:\Users\PeterJ\CLionProjects\CREXX-clean\cmake-build-debug --target all
ninja: error: '../lib/rxfns/rxas/copies.rxbin', needed by 'lib/rxfns/rxas/CMakeFiles/lib_rxas', missing and no known rule to make it

```
Any idea what went wrong?

**Comment by rvjansen** [comment]
looks like copies.rxbin is not there; ninja clean && ninja ?

**Comment by rvjansen** [comment]
it is the one in rxas that is missing - we also have one in rexx - maybe you did not build the lib/rxfns/rxas subdirectory?

**Comment by Peter-Jacob** [comment]
You are right! I thought the RXAS/RXBIN files are constructed by the build process. Once I created them manually the BUILD runs successfully. Maybe I set up a Regina REXX to do it (semi) automatically

**Comment by rvjansen** [comment]
well - they are, or they should be: cmake does it following the cmakelists.txt file. If they are not automatically built, something in the setup is still wrong. There should be really no need to build them by hand or scripts.
