### ISSUE TITLE
compiler fails on wrong style comment

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#289]
I have an emacs mode that sometimes inserts comments after an end in dash dash style - it works in ooRexx and NetRexx and the CREXX mode is the ooRexx mode. The compiler most of the time signals this error, but this particular example is kryptonite:
```
➜  rexx git:(feature/f0038) ✗ cat fail.rexx
options levelb
i=8
do while i<9
  say 'succeeds'
end -- do while
➜  rexx git:(feature/f0038) ✗ rxc fail.rexx
ERROR: Compiler Exiting - Failure
➜  rexx git:(feature/f0038) ✗
```
Checked this into feature/f0038 as lib/rxfns/rexx/fail.rexx. Solving this with the introduction of dash dash comments would also be great.

**Comment by adesutherland** [comment]
Here is a question about "--" line comments.

Consider that in REXX block comments are nested

So should line comments also facilitate (or at least not break) block comments

Eg.

```
/* REXX */
-- More REXX
/* This is a block comment /* Nested 
*/ end of comment */

-- So ...

/* Is /* this 
-- Valid */
? */

-- In sum, should a line comment end at the end of the line, 
-- but also count the */  and /* to support nested block comments?

**Comment by adesutherland** [comment]
BTW - The last line is invalid as the */ is closing a block comment that was not started, if you see what I mean!

**Comment by adesutherland** [comment]
Second debate ... 

Considering that there is a gravitational pull to use C operators as languages are (have) moved to that standard

And so, that "--" is a C operator (which we MIGHT want to adopt at some point), also "//" is a REXX operator (which we MIGHT want to deprecate at some point)

We need a line comment, this is clear.

So my suggestion is that we use "#". The hash is used for a line comment in many languages, and it does not interfere with either C or REXX operators. Therefore I propose we use # for line comments ...

**Comment by rvjansen** [comment]
We *don't* really need a line comment of course, and seeing the arguments (which are all very good) it might be better to not have one in levels other than C(ompatibility). I can comment out something in my editor by selecting an area and press one function key. The problem is that NetRexx and Object Rexx have the `--` comment and that pasting in source is a problem when cReX (like the eye-catcher!) does not have it. Purists have mourned the loss of misusing a minus.

I do not think that a lot of people using Rexx like the `--` or `++` operators of C. 

Regarding 
``-- but also count the */  and /* to support nested block comments? `` - I think everything until eol is thrown out when a `--` starts.

**Comment by adesutherland** [comment]
I will add some options (hashcomments, dashcomments, slashcomments) so we an play - also good to see how the options keyword can be used ...

**Comment by adesutherland** [comment]
And (in the fullness of time) options like (coperators and rexxoperators)

**Comment by rvjansen** [comment]
But to think how I would use it most of the time: I would opt for the Classic Rexx operators most of the time. What would be good, if we are changing these in other cReX levels, would be a block construct to change the dialects. Like in NetRexx you have a 'do binary' (and in Level B cReX we already have an address assembler) so you have a block scope for these decisions.

**Comment by adesutherland** [comment]
Changing operators would be a very difficult "business change and adoption" task that might be beyond us. Something for the strategic future!

**Comment by rvjansen** [comment]
yes, I guess in the Algol and Fortran era people badly wanted to have 'formula translation'.
But what about: having the operators standard Rexx, but leaving us free to enter an operator as Unicode that does what you want it to do?
By the way: assembler had 'OPSYN' - you can define what you want a string to mean.
Related: overloading of operators in oo - this might give an opportunity to have a standard math object operator meanings, and new ones on newer math classes.

**Comment by adesutherland** [comment]
> enter an operator as Unicode 

Possible - but clunky? In truth there are only a few that differ so it probably is not such a big deal 


> overloading of operators in oo - this might give an opportunity to have a standard math object operator meanings, and new ones on newer math classes.

Yes - although it became very complex in C++ so need to make it simple to define

**Comment by adesutherland** [comment]
if f0043 we now have

        Dash '--' line comments. Options dashcomments  / nodashcomments (default)
        Slash '//' line comments. Options slashcomments  / noslashcomments (default)
        Hash '#' line comments. Options hashcomments (default) / nohashcomments

Also the compiler now gives a sensible error with the kryptonite program (i.e. with the default nodashcomments option)

**Comment by rvjansen** [comment]
Consideren fixed in current develop
