### ISSUE TITLE
F0038: IPOW wrong? or generated wrong? goes unnoticed when compiled with optimiser 

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#296]
```rexx
options levelb
slen=2
r = 8
signbit = 1
if signbit then r=r-2**(4*slen)
say r
```
generates
```asm
/*
 * cREXX COMPILER VERSION : cREXX F0040
 * SOURCE                 : powerr.rexx
 * BUILT                  : 2022-05-26 14:49:18
 */

.globals=0

main() .locals=5 .expose=powerr.rexx.main
   * Line 1: slen=2
   load r1,2
   * Line 2: r = 8
   load r2,8
   * Line 3: signbit = 1
   load r3,1
   * Line 4: {IF} signbit
   brf l23iffalse,r3
   * Line 4: {THEN}
   * Line 4: r=r-2**(4*slen)
   imult r4,r1,4
   ipow r4,2,r4
   isub r2,r2,r4
l23iffalse:
   * Line 5: say r
   itos r2
   say r2
   * Line 5:
   ret 0
```
the 2 after IPOW should be in the last position - or the instruction spec is not right. The triggers a 
```
Error Severity 1
21:7 - Error after "ipow", invalid operand, expecting {REG,REG,REG} or {REG,REG,INT}
```
now with the optimiser in play, the following asm is generated:
```asm
.globals=0

main() .locals=2 .expose=powerr.rexx.main
   * Line 2: r = 8
   load r1,8
   * Line 4: r=r-2**(4*slen)
   isub r1,r1,256
   * Line 5: say r
   itos r1
   say r1
   * Line 5:
   ret 0
```
which is fast and correct, but obscures the error in IPOW.

**Comment by adesutherland** [comment]
Peter, now we are in trouble, Rene has found a new way to find bugs!

I think we are missing a *pow reg,int,reg instruction

**Comment by Peter-Jacob** [comment]
be prepared, a one-way ticket to South America is always a good alternative!

**Comment by Peter-Jacob** [comment]
... or we throw him to the wolves.

**Comment by rvjansen** [comment]
I consider the latter a rather harsh measure for disclosing a bug report; the former would be thankfully accepted. Although we have a bit of a situation at Schiphol airport lately.

**Comment by Peter-Jacob** [comment]
I added IPOW_REG_INT_REG 
Unfortunately, I can't test it, as my TS_IPOW translates to the coding described by @rvjansen. Either the coding is wrong, or it is way beyond my horizon.  Is there a way to switch off the optimiser?

```
/*
 * cREXX COMPILER VERSION : cREXX F0040
 * SOURCE                 : ts_ipow
 * BUILT                  : 2022-05-26 18:57:06
 */

.globals=0

main() .locals=2 .expose=ts_ipow.main
   * Line 2: r = 8
   load r1,8
   * Line 4: r=r-2**(4*slen)
   isub r1,r1,256
   * Line 5: say r
   itos r1
   say r1
   * Line 5: 
   ret 0

```

**Comment by rvjansen** [comment]
Yes, there is. Rxc -n etc

**Comment by rvjansen** [comment]
the fix works. Thanks Peter, no need for me dancing with wolves now.

**Comment by adesutherland** [comment]
Use the -n option
