### ISSUE TITLE
dependency failure with cmake generated makefiles (but not with Ninja build)

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#305]
[ 50%] Built target rxbvm
make[2]: *** No rule to make target `lib/rxfns/rxas/library-rxas.rxbin', needed by `lib/rxfns/library.rxbin'.  Stop.
make[1]: *** [lib/rxfns/CMakeFiles/library.dir/all] Error 2
make: *** [all] Error 2
➜  crexx_release

**Comment by rvjansen** [comment]
but fixable with a number of make -k 's - so low priority

**Comment by adesutherland** [comment]
Should be fixed now in develop

**Comment by rvjansen** [comment]
is fixed. Merged into F0038. On Linux/Intel a successful build required a clean checkout (ninja and make); problem probably unrelated but indicative of still missing dependencies. Symptom was missing instructions. No problem for now.
