### ISSUE TITLE
problem building develop with merged f0043

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#313]
[226/362] Building C object compiler/CMakeFiles/rxc.dir/rxcpast.c.o
FAILED: compiler/CMakeFiles/rxc.dir/rxcpast.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I/Users/rvjansen/apps/crexx-develop/compiler -I/Users/rvjansen/apps/crexx_release/compiler -I/Users/rvjansen/apps/crexx-develop/assembler -I/Users/rvjansen/apps/crexx-develop/compiler/../avl_tree -I/Users/rvjansen/apps/crexx-develop/compiler/../machine -I/Users/rvjansen/apps/crexx-develop/compiler/../platform -I/Users/rvjansen/apps/crexx-develop/compiler/../utf8 -I/Users/rvjansen/apps/crexx-develop/machine/. -I/Users/rvjansen/apps/crexx-develop/machine/../platform -I/Users/rvjansen/apps/crexx_release/machine -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu90 -MD -MT compiler/CMakeFiles/rxc.dir/rxcpast.c.o -MF compiler/CMakeFiles/rxc.dir/rxcpast.c.o.d -o compiler/CMakeFiles/rxc.dir/rxcpast.c.o -c /Users/rvjansen/apps/crexx-develop/compiler/rxcpast.c
/Users/rvjansen/apps/crexx-develop/compiler/rxcpast.c:29:30: error: use of undeclared identifier 'TK_EOL'
    if (token->token_type == TK_EOL) {
                             ^
1 error generated.
[228/362] Building C object compiler/CMakeFiles/rxc.dir/rxcpbpar.c.o
FAILED: compiler/CMakeFiles/rxc.dir/rxcpbpar.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I/Users/rvjansen/apps/crexx-develop/compiler -I/Users/rvjansen/apps/crexx_release/compiler -I/Users/rvjansen/apps/crexx-develop/assembler -I/Users/rvjansen/apps/crexx-develop/compiler/../avl_tree -I/Users/rvjansen/apps/crexx-develop/compiler/../machine -I/Users/rvjansen/apps/crexx-develop/compiler/../platform -I/Users/rvjansen/apps/crexx-develop/compiler/../utf8 -I/Users/rvjansen/apps/crexx-develop/machine/. -I/Users/rvjansen/apps/crexx-develop/machine/../platform -I/Users/rvjansen/apps/crexx_release/machine -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu90 -MD -MT compiler/CMakeFiles/rxc.dir/rxcpbpar.c.o -MF compiler/CMakeFiles/rxc.dir/rxcpbpar.c.o.d -o compiler/CMakeFiles/rxc.dir/rxcpbpar.c.o -c /Users/rvjansen/apps/crexx-develop/compiler/rxcpbpar.c
/Users/rvjansen/apps/crexx-develop/compiler/rxcpbpar.c:28:34: error: use of undeclared identifier 'TK_EOL'
        if (token->token_type == TK_EOL) token->token_type = TK_EOC;
                                 ^
/Users/rvjansen/apps/crexx-develop/compiler/rxcpbpar.c:57:65: error: use of undeclared identifier 'TK_EOL'
        if (token_type == TK_COMMA && peek_token->token_type == TK_EOL) {
                                                                ^
/Users/rvjansen/apps/crexx-develop/compiler/rxcpbpar.c:69:27: error: use of undeclared identifier 'TK_MINUSMINUS'
        if (token_type == TK_MINUSMINUS) {
                          ^
3 errors generated.
[237/362] Building C object compiler/CMakeFiles/rxc.dir/rexbscan.c.o
ninja: build stopped: subcommand failed.

**Comment by adesutherland** [comment]
(sigh) It does build honesty but clearly we haven't got the crexx scripts quite right! They hurt my head ...

Can you try the usual fresh pull etc.?

**Comment by rvjansen** [comment]
yes, the clone from scratch does work

**Comment by adesutherland** [comment]
I honestly do keep reviewing all the cmake scripts ... One day they will
work properly!
