### ISSUE TITLE
Linking between CREXX stages (compiler->assembler->VM)

### ISSUE THREAD

**Issue by adesutherland** [adesutherland/CREXX#32]
At the moment we use a file, which might be slow in some environments.

One quick answer might be to allow the stages to stream between each other via pipes. 

Longer term we would bypass the assembler stage - i.e. the compiler emitting threaded binary code directly when in interpreter mode. As an aside, we would probably turn of some slow optimisations also when in interpreter mode.

This is for the future because at the phase we are at, we will need to carefully inspect the output from each stage to find weird bugs!

**Comment by rvjansen** [comment]
I am using a simple makefile and the need for linking is not as acute as I thought back in April:
#
# makefile for crexx programs

.rexx.rxbin:
	rxc $*
	rxas $*
	rxdas $*
	rxvm $*

RX_SRC		:= $(wildcard *.rexx)
RX_OBJS	:= $(RX_SRC:.rexx=.rxbin)

.SUFFIXES: .rexx .rxas .rxbin

#
# target all compiles
#
all::	$(RX_OBJS)

#
# target clean removes compiled products
#
.PHONY: clean
clean:
	rm -f *.rxas
	rm -f *.rxbin

**Comment by rvjansen** [comment]
this is for the kanban
