### ISSUE TITLE
Symbol() BIF is missing

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#333]
We are missing the symbol() bif.

**Comment by Peter-Jacob** [comment]
There are indeed commands I've never used, nor heard: SYMBOL. 
I think I must re-activate/re-sync my CREXX environment.

**Comment by rvjansen** [comment]
"returns the state of the symbol named by name. Returns BAD if name is not a valid REXX symbol. Returns VAR if it is the name of a variable (that is, a symbol that has been assigned a value). Otherwise returns LIT, indicating that it is either a constant symbol or a symbol that has not yet been assigned a value (that is, a literal)." I sometimes use it in combination with DROP.

**Comment by Peter-Jacob** [comment]
@adesutherland can you please guide me to a procedure/array/stack/etc. where I can check current defined variables?

**Comment by Peter-Jacob** [comment]
SYMBOL BIF added to f046, please verify it!

**Comment by rvjansen** [comment]
SYMBOL passed the test cases!
