### ISSUE TITLE
Single quote not supported in comment

### ISSUE THREAD

**Issue by jlfaucher** [adesutherland/CREXX#334]
Tested with cREXX F0044
When compiling the attached file 
[quote_in_comment.txt](https://github.com/adesutherland/CREXX/files/11366652/quote_in_comment.txt)
with rxc
I get
```
Error in quote_in_comment.rexx @ 2:7 - #EXTRANEOUS, "\'"
Error in quote_in_comment.rexx @ 3:7 - #EXTRANEOUS, "\'"
Error in quote_in_comment.rexx @ 4:10 - #SYNTAX_ERROR, "do"
```
(can't use the extension .rexx for the attached file, github says it's not a supported file type)

**Comment by adesutherland** [comment]
Hello!

Please try
```
options levelb dashcomments
-- don'
-- don't
-- don't do that
```
:-)

**Comment by jlfaucher** [comment]
ah, ok... So it was not recognized as a comment.
I have now a Segmentation fault: 11
Testing under macOS Monterey M1
Is it only me?

**Comment by adesutherland** [comment]
No you have found a bug - I will fix it in the next version!

The problem is that it is an empty file - no instructions ...

Please add

    say "hello"

at the end of the file

**Comment by rvjansen** [comment]
Same here, when putting a
```
say 'hello Jean-Louis'
```
behind it, it works - thanks for finding this!

**Comment by adesutherland** [comment]
Well I have made the compiler generate

```
/*
 * cREXX COMPILER VERSION : cREXX F0045
 * SOURCE                 : test.rexx
 * BUILT                  : 2023-05-01 18:44:47
 */

.srcfile="test.rexx"
.globals=0
```

But (quite rightly) the assembler complains

    0:0 - Error no instructions in file

So we will maybe need to have a special "empty file" error code from the compiler to make any scripting allow this edge case scenario to work as expected. Well for future thoughts!

**Comment by adesutherland** [comment]
Well I have made the compiler generate

```
/*
 * cREXX COMPILER VERSION : cREXX F0045
 * SOURCE                 : test.rexx
 * BUILT                  : 2023-05-01 18:44:47
 */

.srcfile="test.rexx"
.globals=0
```

But (quite rightly) the assembler complains

    0:0 - Error no instructions in file

So we will maybe need to have a special "empty file" error code from the compiler to make any scripting allow this edge case scenario to work as expected. Well for future thoughts!
