### ISSUE TITLE
c2x should return the raw bytes of the string (so its UTF-8 encoding) instead of the Unicode scalar values

### ISSUE THREAD

**Issue by jlfaucher** [adesutherland/CREXX#336]
Assumption: the internal representation of the strings is UTF-8, not an array of codepoints resulting of the decoding of the UTF-8 representation.
If this assumption is wrong, then the only problem is the truncated hexadecimal representation.

Illustration:
'DFBF'x is the Utf-8 encoding of the character U+07FF
https://www.compart.com/en/unicode/U+07FF

c2x('DFBF'x) retuns FF
This is the truncated hexadecimal representation of the Unicode scalar value U+07FF
https://www.unicode.org/glossary/#unicode_scalar_value

c2x('DFBF'x) should return DFBF

More examples in [test_c2x.rexx.txt](https://github.com/adesutherland/CREXX/files/11379896/test_c2x.rexx.txt)

**Comment by adesutherland** [comment]
You are right - internally cRexx uses UTF-8, I half regret this decision and wonder if we should have gone for utf-32 instead (some trade-offs between space vs performance vs complexity). Anyway, the important point is this is internal to cRexx.

I agree that c2x should return the full code point (so in general upto 3 bytes) - I gather from google that the largest is '10FFFD'x

An issue we have (and this is a design / specification question) is that not all byte sequences are valid UTF. So in classic REXX programmer's have happily put binary data into variables which, I suspect, were originally intended just to store text. And for fixed 8 bit coding it didn't really matter anyway.

cRexx level B and G is typed. And the missing type (to be done after MVP) is .binary. Seperating .string and .binary will make this all much cleaner. For non-typed REXX languages I guess we will have to define SIGNALS when there are invalid utf coding - something like that.

**Comment by rvjansen** [comment]
So it boils down - I think now - that for some applications we want the (character) code point in hex - but for others, like what Shmuel suggest for STORAGE (which we have on TSO and z/VM, I don't know about other platforms. In particular, if we don't know the internal representation (which can change, see Java and I gather, what I understand, CREXX) or we can't get to storage (Rust?) we can only return codepoints. We do probably want bytes also, but when we cannot get at the storage, we need to add an encoding. This certainly goes for the return trip, X2C - if we don't want code points, we need to add representation. All of this makes me wonder if we need to define C in these BIF names as standing for Character and X for Character Code point, and need new BIFs for hex bytes - or, as a compromise, new Char-2-Hex Codepoint BIFS.

**Comment by adesutherland** [comment]
So from Rony's comment - I think in fact that c2x('DFBF'x) should return FF?

I know I am completely changing my mind - but surely c2x() should return unicode code point?

**Comment by rvjansen** [comment]
This is also my point of view - from the beginning actually. I find the idea of expressing the bytes in Unicode escape (*if they are more than 1 per char*) refreshing though - because with every number it is always good to have the denomination encoded.

René.

**Comment by rvjansen** [comment]
It should return whatever is in its source encoding, even if that is ebcdic or baudot or morse code. Agree that will be utf-8 for most cases today. Will adhere to Unicode ARB decision
