### ISSUE TITLE
Build Improvements

### ISSUE THREAD

**Issue by adesutherland** [adesutherland/CREXX#355]
The Github actions build (and now create a snapshot release) for each commit. But there are some issues.

1/ Execute flag lost in the ZIP files. This should be fixed in f0019.
2/ Need to sign / notarise code for Mac and Windows
3/ Need to build for Apple Intel and Apple Silicon
4/ Need to fix VM370 build
5/ Need to include library.rxbin
6/ Need to include the "Réne wrappers"

**Comment by rvjansen** [comment]
works like a charm. I used a library.rxbin from the mac with it on windows. Windows binaries worked, did a 'search the internet' the first time. I am sure xattrs will work on the mac. Signing is slightly better, I have an Apple developer account.
Apple intel and arm can be a fat binary. 

After this I got the Windows 11 build working (MinGW from Chocolatey did the trick, LLVM and msys2 failed), but I am very happy with the binaries, so we can have people like Walter execute them without building.

**Comment by adesutherland** [comment]
Thanks for testing - I have also edited the issue to remind me to all library.rxbin to the release files. Also we can update the readme file? 

I think users should be pointed in the direction of 'rxvme' which has library.rxbin already in there. Plus we need to see what to do with the "bin" scripts. We should get rid of some by making sure the arguments to the real binaries are sane / consistent. And for wrappers (like a crexx to compile and run in one step) make it a rexx binary and include it in the release (?)

**Comment by adesutherland** [comment]
I have changed f0019 to hopefully have the right exec flag set and create universal binaries (which I can't test).

I do get
```
file rxas
rxas: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
rxas (for architecture x86_64): Mach-O 64-bit executable x86_64
rxas (for architecture arm64):  Mach-O 64-bit executable arm64
adrian@AdriansMacBook assembler % ls
CMakeFiles              cmake_install.cmake     rxas                    rxasgrmr.h              rxasscan.c
CTestTestfile.cmake     librxaslib.a            rxasgrmr.c              rxasgrmr.out
adrian@AdriansMacBook assembler % file librxaslib.a 
librxaslib.a: Mach-O universal binary with 2 architectures: [x86_64:current ar archive random library] [arm64:current ar archive random library]
librxaslib.a (for architecture x86_64): current ar archive random library
librxaslib.a (for architecture arm64):  current ar archive random library
```
Promising but Réne do you mind checking the F0019 Release snapshot in the created release zip? Thanks

**Comment by rvjansen** [comment]
That works, after doing a sudo xattr -r -d com.apple.quarantine *  in the directory that needs executing of the files therein.
Tested on the M1; if they work on your X86_64 we're ok. I still have one Xeon Mac Pro in the attic but it is a heavy thing.

**Comment by rvjansen** [comment]
that seems fixed.
