### ISSUE TITLE
f0049: IS_A_NAMESPACE error with unquoted string

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#356]
Did a small smoke test while working on something else. Forgot to quote 'hello'; an IS_A_NAMESPACE,"hello" error came out. 
Do not know what triggered this. When quoted, everything is fine.
```
options levelb
import rxfnsb

say hello
say date('j')
exit
```

```
➜  scratch crexx hello
Error in hello.rexx @ 4:5 - #IS_A_NAMESPACE, "hello"
Error in hello.rexx @ 4:5 - #UNKNOWN_TYPE, "hello"
2 error(s) in source file
hello
2023200
```

**Comment by adesutherland** [comment]
As designed ... (if not actually documented!)

If the namespace instruction is not used the namespace is set to the file name (i.e. hello).

Then you try and use hello as a variable (all be it, taken as a constant literal) and the compiler complains ...

**Comment by rvjansen** [comment]
Ha OK - clear.

René.

**Comment by rvjansen** [comment]
closed as WAD
