### ISSUE TITLE
SAYX REG missing

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#409]
SAYX taking a string is working OK
SAYX taking a REG is missing
is defined and shown in rxas -i but seems to be missing from rxvmintp.c

**Comment by Peter-Jacob** [comment]
Theoretically, it should have been an easy task – or so I naively thought!
But, of course, now the whole thing refuses to compile. See new issue

**Comment by rvjansen** [comment]
With apologies to mr Kernighan and mr Richie. This is now also fixed, as the wonkyness experienced in the new SAYX was caused by a typo in my test program - which will lead to another bug report, as typos may not be allowed to cause traps.
