### ISSUE TITLE
say 'hello' fails with single quotes, succeeds with double quotes

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#41]
my profound apologies for this report, but I am starting to test and this was the first observation. A 'hello crexx world' with single quotes fails. As I might have been told.

**Comment by adesutherland** [comment]
Error is in the compiler

**Comment by rvjansen** [comment]
in F0011, this now says:
hello crexx!
0

**Comment by rvjansen** [comment]
works OK in v0.1.6-i0053
