### ISSUE TITLE
segfault in rxc

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#63]
On macOS 11.5.1, on X86-64 as well as ARM64 with rxc from cREXX-Phase-0 v0.1.6 + F0026,  a segfault occurs with the following program:

➜  test git:(master) ✗ cat mullerkahan.rexx
/* rexx
 * muller-kahan test for floating point correctness
 * the correct answer is 100
 * modern processor floating point, i.e. i7 or m1 yields 99.8985692661829
 * oorexx: 100.0
 * brexx : 99.8985692661829034477705135942
 */
options levelb
max = 21
u = 2.0
v = -4.0
do i=3 to max
  w = 111.0 - 1130.0/v + 3000.0/(v*u)
  u = v
  v = w
end
say v

➜  test git:(master) ✗ sudo lldb ~/apps/crexx_debug/compiler/rxc mullerkahan
(lldb) target create "/Users/rvjansen/apps/crexx_debug/compiler/rxc"
Current executable set to '/Users/rvjansen/apps/crexx_debug/compiler/rxc' (x86_64).
(lldb) settings set -- target.run-args  "mullerkahan"
(lldb) run
Process 61396 launched: '/Users/rvjansen/apps/crexx_debug/compiler/rxc' (x86_64)
Process 61396 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xc)
    frame #0: 0x0000000100056fa3 rxc`emit_walker(direction=out, node=0x0000000100307440, pl=0x00007ffeefbff460) at rxcpemit.c:1080:25
   1077	                                 node->parent->register_num);
   1078	                    }
   1079	                    else {
-> 1080	                        snprintf(temp1, buf_len, "   %sadd r%d,r%d,1.0\n",
   1081	                                 tp_prefix,
   1082	                                 node->parent->register_num,
   1083	                                 node->child->register_num,
Target 0: (rxc) stopped.
(lldb)

**Comment by adesutherland** [comment]
What a great bug! :-)

The program shows 3 bugs (at least): 
- an issue with the emitter trying to use a child node that does not exist (the seg fault)
- the optimiser getting rid of the "i" thinking it is a constant
- rxas not handling negative floats(!)

I will have to fix if f0028

Also - f0028 will be closed with just handling embedded assembler so we can get it into dev asap

A

**Comment by adesutherland** [comment]
Works in the latest check f0028. But the question is should cREXX be using long double for floats ....

**Comment by rvjansen** [comment]
Works! 
About the long double type: I think that when we (for a reason) introduce hardware-native types, there is no real point in trying to determine which one serves which application; long double would add some digits here probably, but I think it would be better to introduce separate float and long double options, either as option or as (shudder) type declaration. (Like NetRexx: variable=type as a first mention). This would introduce the very interesting (from my point of view) introducing decimal floating point on architectures that have it. But I think this is very low priority at the moment; happy that this already works.
