### ISSUE TITLE
segfault in rxas with tab in source

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#64]
all platforms.
cREXX-Phase-0 v0.1.6 + F0026

➜  refcards git:(feature/f0004) ✗ sudo lldb ~/apps/crexx_debug/assembler/rxas func1
(lldb) target create "/Users/rvjansen/apps/crexx_debug/assembler/rxas"
Current executable set to '/Users/rvjansen/apps/crexx_debug/assembler/rxas' (x86_64).
(lldb) settings set -- target.run-args  "func1"
(lldb) run
Process 62793 launched: '/Users/rvjansen/apps/crexx_debug/assembler/rxas' (x86_64)
Process 62793 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000100015c94 rxas`rxasexre(context=0x00007ffeefbff400, registerToken=0x0000000100208bb0, exposeToken=0x0000000100208dc0) at rxasassm.c:225:9
   222 	        err_at(context, registerToken, "duplicate exposed register");
   223 	    }
   224 	    else context->extern_regs[(int)registerToken->token_value.integer] = 1;
-> 225
   226 	    /* Add the entry to the constants pool */
   227 	    entry_size =
   228 	            sizeof(expose_reg_constant) +
Target 0: (rxas) stopped.
(lldb)

* source file func1.rxas
	 .globals=1
g0 .expose=my.exposed_global
log()    .expose=my.log
func1()  .locals=3 .expose=global.func1
         load r1,1
         load r2,"In func1()"
         call r0,log(),r1
         ret
say_exposed_g() .locals=1 .expose=global.say_exposed_g
         load r0,"exposed global="
         itos g0
         concat r0,r0,g0
         say r0
         ret

before .globals, there is a tab instead of spaces, as can be seen in the hexdump below (due to emacs asm mode, which I since changed) 

00000000: 2a20 736f 7572 6365 2066 696c 6520 6675  * source file fu
00000010: 6e63 312e 7278 6173 0a09 202e 676c 6f62  nc1.rxas.. .glob
00000020: 616c 733d 310a 6730 202e 6578 706f 7365  als=1.g0 .expose
00000030: 3d6d 792e 6578 706f 7365 645f 676c 6f62  =my.exposed_glob
00000040: 616c 0a6c 6f67 2829 2020 2020 2e65 7870  al.log()    .exp
00000050: 6f73 653d 6d79 2e6c 6f67 0a66 756e 6331  ose=my.log.func1
00000060: 2829 2020 2e6c 6f63 616c 733d 3320 2e65  ()  .locals=3 .e
00000070: 7870 6f73 653d 676c 6f62 616c 2e66 756e  xpose=global.fun
00000080: 6331 0a20 2020 2020 2020 2020 6c6f 6164  c1.         load
00000090: 2072 312c 310a 2020 2020 2020 2020 206c   r1,1.         l
000000a0: 6f61 6420 7232 2c22 496e 2066 756e 6331  oad r2,"In func1
000000b0: 2829 220a 2020 2020 2020 2020 2063 616c  ()".         cal
000000c0: 6c20 7230 2c6c 6f67 2829 2c72 310a 2020  l r0,log(),r1.
000000d0: 2020 2020 2020 2072 6574 0a73 6179 5f65         ret.say_e
000000e0: 7870 6f73 6564 5f67 2829 202e 6c6f 6361  xposed_g() .loca
000000f0: 6c73 3d31 202e 6578 706f 7365 3d67 6c6f  ls=1 .expose=glo
00000100: 6261 6c2e 7361 795f 6578 706f 7365 645f  bal.say_exposed_
00000110: 670a 2020 2020 2020 2020 206c 6f61 6420  g.         load
00000120: 7230 2c22 6578 706f 7365 6420 676c 6f62  r0,"exposed glob
00000130: 616c 3d22 0a20 2020 2020 2020 2020 6974  al=".         it
00000140: 6f73 2067 300a 2020 2020 2020 2020 2063  os g0.         c
00000150: 6f6e 6361 7420 7230 2c72 302c 6730 0a20  oncat r0,r0,g0.
00000160: 2020 2020 2020 2020 7361 7920 7230 0a20          say r0.
00000170: 2020 2020 2020 2020 7265 740a                    ret.

**Comment by adesutherland** [comment]
I have hopefully fixed the tab issue (it was a UTF issue) it is in the latest f0028 branch if you want to test

A :-)

**Comment by rvjansen** [comment]
works in f0028
