### ISSUE TITLE
order of .expose statements confuses rxas

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#66]
this fails:
```
.globals=2

length()   .expose=global.length
g1 .expose=exposed_global.g1          

    
main() .locals=3
          load r1,"Test"
          load r2,"of Length function"
          sconcat r2,r1,r2
          say r2

          load g1,"the quick brown fox jumps over the"
          call r1,length(),g1
          itos r1
          say r1 
          ret

```
with Error Severity 1
0:0 - Error completely confused

while this works:
```
.globals=2
g1 .expose=exposed_global.g1          
length()   .expose=global.length


    
main() .locals=3
          load r1,"Test"
          load r2,"of Length function"
          sconcat r2,r1,r2
          say r2

          load g1,"the quick brown fox jumps over the"
          call r1,length(),g1
          itos r1
          say r1 
          ret
```

**Comment by rvjansen** [comment]
well, let me then also proudly present my first Rexx function:
```
.globals=2

g0         .expose=exposed_global.g1          
length()   .locals=4 .expose=global.length
          say "I am in length()"
          load  r3,0
          say   g0
          strlen r3,g0
          ret r3
```
which yields, with the working test of the above:

➜  rxasm git:(master) ✗ rxvm testlength length
Test of Length function
I am in length()
the quick brown fox jumps over the
34

**Comment by adesutherland** [comment]
This is not tested but can you try:

.globals=0

length()   .expose=global.length
    
main() .locals=5
          load r1,"Test"
          load r2,"of Length function"
          sconcat r2,r1,r2
          say r2

          load r3,1 /* There is one argument - which must be in r4 - i.e. the next register after r3 */
          load r4,"the quick brown fox jumps over the"
          call r1,length(),r3 /* i.e. you pass the register containing the number of arguments then the first argument must be in r4 then r5 etc */
          itos r1
          say r1 
          ret


And


.globals=0

length()   .locals=4 .expose=global.length
          say "I am in length()"
          load  r3,0
          itos a0
          say a0 /* This should say 1 - the number of arguments */
          say a1 /* This should say "the quick ..." */
          strlen r3,a1
          ret r3

/* Remember r1 in main() is NOT the same register as r1 in length()  - length() gets its own registers */

**Comment by adesutherland** [comment]
> this fails:
> 
> ```
> .globals=2
> 
> length()   .expose=global.length
> g1 .expose=exposed_global.g1          
> 
>     
> main() .locals=3
>           load r1,"Test"
>           load r2,"of Length function"
>           sconcat r2,r1,r2
>           say r2
> 
>           load g1,"the quick brown fox jumps over the"
>           call r1,length(),g1
>           itos r1
>           say r1 
>           ret
> ```
> 
> with Error Severity 1
> 0:0 - Error completely confused
> 
> while this works:
> 
> ```
> .globals=2
> g1 .expose=exposed_global.g1          
> length()   .expose=global.length
> 
> 
>     
> main() .locals=3
>           load r1,"Test"
>           load r2,"of Length function"
>           sconcat r2,r1,r2
>           say r2
> 
>           load g1,"the quick brown fox jumps over the"
>           call r1,length(),g1
>           itos r1
>           say r1 
>           ret
> ```

This is by design - but I will try and fix the error message (!) - the global variables must come first. I will investigate to see if we can make this better more flexible

A

**Comment by rvjansen** [comment]
yes, this works and does not need global variables

so the linkage convention would be:
first reg has number of arguments
next regs have arguments

good, with length() in place I can now make substr(), which needs to check number of args, loop for length(). I think.

I tried putting this assembler length() in Rexx, but that fails:

/* rexx length function */
options levelb
assembler 
do
.globals=2

g0        .expose=exposed_global.g1          
length()  .locals=4 .expose=global.length
          load  r3,0
          strlen r3,g0
          ret r3
end
return a

will try again with the global-less version.

best regards,

René.

**Comment by adesutherland** [comment]
Assembly in rexx only allows instructions which are then inserted into the
generated overall assembler. Not directives.

But you could do

Thestring = "blah"
Result = 0
Assembler strlen result,thestring
Say result

A

**Comment by rvjansen** [comment]
yes, but if we want to write a function in a rexx file, and want to use assembler in there, it would need to be a global symbol, otherwise it cannot be linked? Or can we generate this in the overall assembler, and then use args() and arg() for the arguments?

René.

**Comment by adesutherland** [comment]
Yes - in REXX Level B we need a way to expose/export functions - and build a library. And for classic REXX code to automatically link against the classic REXX runtime library. 

I am working on REXX PROCEDURE now - I think seeing it in action will make it clearer and help work out what features we need to write and link the REXX (Level C) runtime library which will be developed in REXX (level B).
