### ISSUE TITLE
optimizer eliminates more than it should

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#67]
in cREXX-Phase-0 v0.1.6 + F0028, in the rexxasm example, even when given a large loop size:

```
/* */
options levelb

say "starting"
start_time = 0
end_time = 0
a = 0
assembler say "hello"
assembler do
  itos a
  say a
end
assembler time start_time
do i = 1 to 1000000000000000
  a = a + i
end
assembler time end_time

say "Time taken is" end_time-start_time "seconds"

```
the generated rxasm is:
l28:
   * Line 18: say "Time taken is" end_time-start_time "seconds"
   say "Time taken is 0 seconds"
   exit

**Comment by adesutherland** [comment]
The perfect optimiser as "a" is never used!!!

Only joking - the optimiser is nowhere near smart enough to do that yet ...

It works on the code on my PC so I am thinking it might be a temporary bug ... I will push a snapshot this evening to see it it fixes it for you. A

**Comment by rvjansen** [comment]
ok, will try again when the new code drops.

**Comment by rvjansen** [comment]
this works in the current state of affairs
