### ISSUE TITLE
CMAKE Version and Ubuntu

### ISSUE THREAD

**Issue by adesutherland** [adesutherland/CREXX#8]
Version required in cREXX is 3.17
Version delivered in Ubunu 20.04 is 3.16

Note the re2c has its own CMAKE config but this only requires cmake 3.12

So - can we move to 3.16? Action to check ...

For @rvjansen

**Comment by mgrossmann** [comment]
what is the current state of this issue?
could it be closed as resolved?

**Comment by rvjansen** [comment]
Resolved.
