### ISSUE TITLE
strchar positioning error in some situations

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#81]
There seem to be a positioning error in the strchar routine (via UTF8). It positions wrongly in some situations

```
main()   .locals=16
   load r1,"         1         2         3         4"
   say r1
   load r1,"1234567890123456789012345678901234567890123"
   say r1
   load r1,"The quick brown fox jumps over the lazy dog"
   say r1
   load r4,22   /* substr offset */
   load r5,5    /* substr length */
   load r12,""
substr:
   iadd r12,R4,R5   /* max offset length=offset+requested length */
loop:
   **strchar r11,r1,r4**
   appendchar r12,r11
   load r10,"position "
   itos r4
   concat r10,r10,r4
   say r10
   load r10,"  single Char "
   itos r11
   concat r10,r10,r11
   say r10
   bct r5,r4,loop
   say r12
   ret
```

**if you start the asm with string r4 at position 22** it correctly returns **umps[blank]**

The quick brown fox jumps over the lazy dog
position 22
  single Char 117
position 23
  single Char 109
position 24
  single Char 112
position 25
  single Char 115
position 26
  single Char 32
umps

**if you start the asm with string r4 at position 23** it also returns **umps** instead of **mps[blank]o**

1234567890123456789012345678901234567890123
The quick brown fox jumps over the lazy dog
position 23
  single Char 117
position 24
  single Char 109
position 25
  single Char 112
position 26
  single Char 115
position 27
  single Char 32
umps

**Comment by rvjansen** [comment]
ah thanks. That might have been the reason for me to spend an inordinate amount of time on substr(), and having right() working correctly but left() - which is easier - not

**Comment by rvjansen** [comment]
also, which might be relevant, only on Ubuntu aarch64 I saw spurious characters now and then, on both the arm64 and X86_64 versions of macOS I did not.

**Comment by rvjansen** [comment]
something spooky going on. I don't get any output:
```
234567890123456789012345678901234567890123
The quick brown fox jumps over the lazy dog
position 22
  single Char 0
position 23
  single Char 0
position 24
  single Char 0
position 25
  single Char 0
position 26
  single Char 0
```

**Comment by rvjansen** [comment]
(and yes, I pulled f0030 before building)

**Comment by rvjansen** [comment]
as the substr, left, right etc tests are still working, I suspect my BCT or STRCHAR is not up to date

**Comment by Peter-Jacob** [comment]
I pushed everything. But I have loads of changes in modules that I never touched.
![Screenshot 2021-08-30 14 31 29](https://user-images.githubusercontent.com/46247351/131339403-ffa92166-a9bf-45b1-8cc3-fc581f787874.png)

**Comment by rvjansen** [comment]
I never really trust gui shells on version management, so I always command line. I have to go to a birthday party, but I'll trace tonight to see if I can see if there is something wrong.

**Comment by rvjansen** [comment]
ha I looked a bit better now, and I finally saw your strchar was commented out (so conditioned to see comment in green, but did not adapt asm-mode to * (asterisk) yet. All is fine.
That is: yes, there is a bug in strchar and I am happy you found it.

**Comment by adesutherland** [comment]
22/23 is half way through the string - so string_set_byte_pos() will find the character either from the beginning or the end of the string - this is where the bug must be, I will investigate.

I note you, Peter, delete 1 from the index so maybe it it the "from the beginning" that is wrong ... anyway this explains weird bugs you and Rene were finding. Sorry!

**Comment by Peter-Jacob** [comment]
> 22/23 is half way through the string - so string_set_byte_pos() will find the character either from the beginning or the end of the string - this is where the bug must be, I will investigate.
> 
> I note you, Peter, delete 1 from the index so maybe it it the "from the beginning" that is wrong ... anyway this explains weird bugs you and Rene were finding. Sorry!

There is absolutely no reason to be sorry. Only people who don't work make no errors.

**Comment by rvjansen** [comment]
I wholeheartedly agree.
Can we rebase f0030 on develop? I would like functions *and* bct!

René.

**Comment by adesutherland** [comment]
I have pushed a fix (hopefully a fix) in develop. I also took away the -1 from the index - strchar in summary it is zero based (for consistency) 

Also - bct is fine for assembler programmers but be aware that a compiler could not use it. Also can the branch target be the first argument for consistency?

I suggest you don't rebase - just merge develop into f0030

**Comment by rvjansen** [comment]
I have merged. Substr is back to the drawing board - tomorrow. The function call is great. Two questions though - the declarations need to go path the end, right? I had one in the middle between two calls, and that fails (runtime, not compilation:
```
/* */
options levelb

say "Length of René is" length("René")

length: procedure = .int
  arg string1 = .string

say substr('1234567890','6',0,'')
say substr('1234567890','6',7,'.')


substr: procedure = .string
arg string1 = .string, start=.int, length=.int, pad=.string
```

```
➜  rxasm git:(master) ✗ rxvm testsubstring length substr
7890
7890
Length of René is 0
```

But when they are all at the end, it works:

```
➜  rxasm git:(master) ✗ rxvm testsubstring length substr
Length of René is 4
7890
7890^
```

But substr needs to be revised.

One more question: Substring has 2-4 arguments, with the last two optional. When I leave these out of the declaration, it gives me a message about wrong number of arguments, but when I declare them all, I have to supply them all. Is there a mechanism to indicate the last two are optional?

**Comment by rvjansen** [comment]
Ok, fixed substr.rxas and left.rxas to work with the fixed strchar

**Comment by Peter-Jacob** [comment]
it doesn't loose a character anymore, but position starts now one too late. @adrian, you removed the -1 to get the offset, I think this is the problem. 
         1         2         3         4
1234567890123456789012345678901234567890123
The quick brown fox jumps over the lazy dog
**position 22**
  single Char 109
position 23
  single Char 112
position 24
  single Char 115
position 25
  single Char 32
position 26
  single Char 111
**mps o**


         1         2         3         4
1234567890123456789012345678901234567890123
The quick brown fox jumps over the lazy dog
**position 23**
  single Char 112
position 24
  single Char 115
position 25
  single Char 32
position 26
  single Char 111
position 27
  single Char 118
**ps ov**

Process finished with exit code 0

**Comment by adesutherland** [comment]
Hi Peter ... For RXAS we have to decide if the first character of a string
is number 0 or 1.

At the moment they are all 0 (which is why I changed strchar to be
consistent). This means rexx bifs have to subtract 1, but it means the c
micro code is more natural.

We could change ALL (to be consistent) the instructions to be 1 based
instead. I see this as mainly stylistic with no specific performance
considerations as the subtraction has to happen somewhere, but in this I
might be wrong!

So I appreciate REXX is one based ... happy to go with the majority on this
one 🙂 What does everyone think?

**Comment by Peter-Jacob** [comment]
I don't really mind. in the context of assembler the starting position 0 seems more logical. Do you translate in the rxc process the positions to offsets? If you do, we remain with strings starting at position 0.

**Comment by adesutherland** [comment]
Rene. The declarations can in theory be anywhere. HOWEVER in practice this is only true if the code only has procedures not "free" instructions outside of an explicit procedure - for parsing reasons. 

In your first example the parser must assume that the "say substr(..." is part of the length procedure. I will update the syntax to see is this can be fixed ... the syntax is stop-gap to get something working.

Optional parameters will be supported but are not there yet ...

The syntax is likely to be 

Arg a = 0

Showing a is a integer with a default value of 0 if it is not specified by the caller

Also 

Arg ... = .int

Show arbitrary number of int arguments

**Comment by rvjansen** [comment]
About the offset. I don't mind. I am just worrying that *if* we put a lot of the infrastructure together in Rexx, it will look funny. For the assembler I don't mind - yesterday this just cost me 10 minutes (Arubian minutes that is)  and two isub's to get it working again. But let us first make some functions in Rexx itself and see how it looks.

**Comment by adesutherland** [comment]
> I don't really mind. in the context of assembler the starting position 0 seems more logical. Do you translate in the rxc process the positions to offsets? If you do, we remain with strings starting at position 0.

No - the BIFS will have to do the translation. Lets see what the BIFs look like and decide - we have the advantage of being able to change the CPU at whim!
