### ISSUE TITLE
something wrong with concchar?

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CREXX#93]
Peter, could you have a look at the checked-in f0030 lib/rxfns/substr.rxas (and it corresponding testsubstr?) 
I tried to work the concchar and bct instructions in there, but it seems the concat of pad does not work. What am I doing wrong here? (I left some debug in).

**Comment by Peter-Jacob** [comment]
I think there is a misunderstanding with CONCHAR: 
pad:
```
    concchar r14,r7,a2
    say "we are padding with"
    say r7
    itos r12
    say r12
    say  r14
    itos a2
    say a2
    bct   pad,r12,a2
```

concchar adds r7[a2] to r14, it works for the first time, but then it addresses r7[2],r7[3] which is undefined. you should use appendchar instead.

**Comment by rvjansen** [comment]
ok, I get that. But when I change that to concat, like in your mid() ... it still does not concat.
Can you have a look? It is checked in.

**Comment by rvjansen** [comment]
there is def something with concat:
concat r14,14,r7 does not concat
concat r14,r7,r14 does concat (but I cannot use that, as it is the wrong way around)

your suggested variants give me:
55:10 - Error after "concat", invalid operand, expecting {REG,REG,REG}, {REG,REG,STRING} or {REG,STRING,REG}

**Comment by rvjansen** [comment]
My guess is that the strpointer is messed up somewhere. I have to read Adrian's earlier appends

**Comment by Peter-Jacob** [comment]
concat doesn't allow an integer value as input, so 
load   r?, 0          r? is register of your choice 
concat r14,r7,r?   should work 

if not try setting r? to 1 as an alternative. I am not sure if the change of position to offset took consistently place

**Comment by rvjansen** [comment]
by the way, I have moved the directory one level down - sorry for that, but I want to make room for the Rexx versions of these functions, the "zero" level (like the java zero vm, which does no optimization whatsoever, but is always the first one to be ported). Also added 'native' for future developments

**Comment by Peter-Jacob** [comment]
ok, fetched it!

**Comment by Peter-Jacob** [comment]
Are you showing the bif samples tonight? I am not sure if I get my calling problem resolved

**Comment by Peter-Jacob** [comment]
don't worry for me it's not an obstacle, once resolved the conversion into bifs takes place in a breath.

**Comment by rvjansen** [comment]
yes I had appendchar, but I wanted to work Peter's solution into the source so I could measure the difference - and then I stumbled upon this

**Comment by rvjansen** [comment]
> Are you showing the bif samples tonight? I am not sure if I get my calling problem resolved

yes, will do.

**Comment by rvjansen** [comment]
so - when we look at oldsubstr, the concat r14,r14,r7 works perfectly. In the current substr.rxas it does not. Even appendchar does not work.
But: concat r14,r7,r14 does work - but I can't use that for padding at the back.
Referring to the title of this issue: I think concchar leaves the string in an undesired state

**Comment by rvjansen** [comment]
but let me work on it for a while to see if the problem is not between the screen and the keyboard

**Comment by Peter-Jacob** [comment]
mine are always between the ears ;)

**Comment by rvjansen** [comment]
fixed this, while stealing most of Peter's design. I got a clue when running the debug version of rxvm with tracing on under gdb - this told me where exactly that assertion for string ptr did fail. The only thing left to clean up was that Peter's  version did not account for a call without length. Short version: concchar is fine, I had string overruns that were hard to see on mac (where all overruns where delivered as blanks) and linux (different results on different architectures). Do we need to protect the string functions against people like me? The assert did help, but probably will cost performance.

**Comment by Peter-Jacob** [comment]
I had assertion errors quite often, it always meant: string overrun. I am surprised it behaves differently in various environments.  
I wonder if we should create a generic parameter testing function to allow basic testing. Currently, each function has its own, or none (most of mine). 

PARMTEST(parameter,variable-type[,low-value-integer[,high-value-integer]])

example:
PARMTEST(a1,'STRING')     a1 must be a string else error message and stop
PARMTEST(a2,'INT',1)         a2 must be an integer, low value >=1, high-value undefined
PARMTEST(a2,'INT',1,lengt(a1))   a2 integer, low-value>=1, but LE length of string a1

**Comment by adesutherland** [comment]
Are you talking about parameter checks in the BIFS or in the RXAS instructions?

**Comment by rvjansen** [comment]
I meant the rxas instructions. I think the differences are mainly how pages in storage are initialised.
